project_id = "lcfsuhdcexrbqevdojlw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-payment-intent]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.redeem-ticket]
verify_jwt = true

[functions.redeem-voucher]
verify_jwt = true

[functions.redeem-order]
verify_jwt = true

[functions.update-user-role]
verify_jwt = true

[functions.audit-log]
verify_jwt = true

[functions.join-cash-game-queue]
verify_jwt = true

[functions.update-queue-status]
verify_jwt = true

[functions.create-order]
verify_jwt = true

[functions.claim-seat-from-hold]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.release-expired-holds]
verify_jwt = false

[functions.redeem-reward]
verify_jwt = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
# Inbucket web interface
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = {"enabled": true}